pipeline {

    agent {
    
    	label 'buildconductor-bpm'
    //    docker { 
    //      image 'greghodgkinson/jenkins-buildconductor-bpm'                 
    //    }
    }
    
    stages {     
        
        stage('Build') {      
        
            steps {
                               
            	sh '/buildconductor/bpm/run-automation-bpm.sh build HW 0.61 Main 10.0.10.166 20005 ghodgkinson ghodgkinson Staging ghodgkinson passw0rd ${BUILD_NUMBER} ${BUILD_URL} ${NODE_NAME}'               
            }
        }
        
        stage('Publish to UCD') {
        	steps {
        	
        	sh "Can we see the offline package file?"   
        	sh "ls -la ${WORKSPACE}"               
            }                        	 	
        }
    }
}